# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '0 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      filter:
        description: 'A filter for pull requests'
        default: '--author ericLemanissier'
        required: false
        type: string


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: "repo"
      - uses: actions/checkout@v3
        with:
          ref: "gh-pages"
          path: "pages"
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - run: "pip3 install requests"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python repo/pr_status.py ${{ github.event.inputs.filter }} > pages/index.md
          pushd pages
          git add index.md
          git commit -m "CI update" || exit(0)
          git push origin gh-pages
          popd
