# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '0 * * * *'


jobs:
  ericLemanissier:
    uses: ./.github/workflows/manual.yml
    with:
      filter: --author ericLemanissier
      page: index

  global:
    uses: ./.github/workflows/manual.yml
    with:
      filter: ''
      page: index
