# This is a basic workflow to help you get started with Actions

name: Manual

on:
  workflow_dispatch:
    inputs:
      filter:
        description: 'A filter for pull requests'
        default: '--author ericLemanissier'
        required: false
        type: string
      page:
        description: 'The output page name'
        default: 'custom'
        required: true
        type: string
  workflow_call:
    inputs:
      filter:
        description: 'A filter for pull requests'
        default: '--author ericLemanissier'
        required: false
        type: string
      page:
        description: 'The output page name'
        default: 'custom'
        required: true
        type: string


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - run: "pip3 install requests"

      - name: Generate web page
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir pages
          python pr_status.py ${{ inputs.filter }} | tee pages/${{ inputs.page }}.md
          
      - name: Deploy 
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages # The branch the action should deploy to.
          publish_dir: pages # The folder the action should deploy.
          keep_files: true
